### ISSUE TITLE
[BUG] application.yml needs to be updated to remove white space in profile sections

### ISSUE THREAD

**Issue by gala-dan** [GalateaRaj/fuse-starter-java#66]
White space is significant within the Spring profiles sections. This means the following:

```
spring: 
    profiles: foo
    datasource: 
        username: sa 
        password: 
```

```
Should actually be:
spring: 
    profiles: foo
datasource: 
    username: sa 
    password: 
```

With the additional white space the settings are not found by Spring.
